"""empty message

Revision ID: 8531c88420aa
Revises: a2338399f94b
Create Date: 2025-02-17 16:04:44.305823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8531c88420aa'
down_revision = 'a2338399f94b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_password', sa.Boolean(), nullable=True))
        batch_op.drop_column('password_reset')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('change_password')

    # ### end Alembic commands ###
